plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[7.0.23,8.0)'
}

version = mod_version
group = mod_group_id
base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        configureEach {
            workingDir.convention layout.projectDirectory.dir('run')
            args "--mixin.config=${mod_id}.mixins.json"
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }
        register('client') {
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:1.21-$forge_version")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar', Jar) {
    manifest {
        attributes['MixinConfigs'] = "${mod_id}.mixins.json"
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
}